### ISSUE TITLE
Question regarding Basic simulation 

### ISSUE THREAD

**Issue by deminyau** [NeverOnTimeSdnBhd/Delivery-Instances#1]
Good Day.

Question regarding Basic simulation 

For basic simulation 

1) Why we evaluate Vertex with id 4 first instead of 2,1,3
Since bfs/dfs is blind search algo, shoudn't we start from vertex with id 1? (the head should be warehouse node)

2) In vehicle 3, why will we go from 0->3->1->0, (we understand that the capacity of truck is not full so can add more customers)
Can we use 0->4->1->0 or 0->2->1->0 instead since they are the same concept. 

3) Similarly to question 3, why can't we tranverse 0->1->3->0? Are there any algorithm for the evaluation of nodes? (Based on distance, id etc)
In the example output, it seems like every sequence of evaluated node are randomize.

4) We are required to do only one of the searching technique right since it wrote in the question BFS / DFS

Thank you for taking your time to answer our questions!

**Comment by NeverOnTimeSdnBhd** [comment]
Hi
First of all, thanks for your questions and sorry for the parts I didn't make it clear.

1. Yes, logically it should always explore node with ID=1 first before 2, and followed by 3, 4, ..., N. When I am coding the sample solution for this question, I used some quick trick so that I can code less (yes I am lazy definitely), I am not using the conventional DFS/BFS. Thus, if you traverse your DFS/BFS search tree from ID 1 to N, then you should get 0 -> 1 -> 3 -> 0 for third route. In fact, this is just a matter of how you traverse the whole graph. There is no rule saying that you must always search from ID 1 so sequence is really not a matter here (as long as you are sure that the final tour found is having the lowest cost).

2. Nope, we can't use 0 -> 4 -> 1 -> 0 or 0 -> 2 -> 1 -> 0, these two routes will result in higher cost (distance travelled by vehicles) in total. _(I will upload these two solutions with higher costs here later so that you can see better)_

3. I think this question is similar to Q1, yes you definitely can do 0 -> 1 -> 3 -> 0 as the order doesn't matter here (by order I mean reading the route from front or back, not the order of every node in a route).

4. Yes, either one.

**Comment by deminyau** [comment]
Good Day.

1) Can use different package for different solution so that the code is more tidy? Because we divide the tasks among group members

2) Can we use tree to fulfill BFS/DFS output? If no, can we use sequential traversal with reference to euclidean distance? If both approach is not correct, may we know what is the correct approach?

Thank you for taking your time to answer our questions!

**Comment by deminyau** [comment]
Thank you 😆

**Comment by zulfathihanafi** [comment]
Hi admin,
May I ask for the Basic Simulation, we need to use either DFS/BFS for our search, but if i'm not mistaken, we learn in class that both search is uninformed search(does not take any cost into account). So how to implement it in this case,as we need to return the cost?

**Comment by NeverOnTimeSdnBhd** [comment]
Hi

Since some of you are keep confusing about DFS/BFS implementation, hence I created a documentation for the clarification. Here is the link: [Basic Simulation](https://github.com/NeverOnTimeSdnBhd/Delivery-Instances/blob/main/update/Basic%20Simulation.md)
Please have a read on that and if you still don't understand any concept or require further clarification then can raise the issue again.

Thanks!
